extends:
  - "@commitlint/config-conventional"

rules:
  type-enum:
    - 2
    - always
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - reapply
      - style
      - test
  scope-enum:
    - 2
    - always
    - - archiver
      - atomicfile
      - audit
      - ci
      - cli
      - cmd
      - collect
      - config
      - deps
      - fsid
      - logtest
      - manifest
      - orgscope
      - progress
      - registry
      - remote
      - seal
      - serialize
      - stacks
      - store
      - tfeclient
      - workspace
  header-max-length:
    - 2
    - always
    - 89
  body-max-line-length:
    - 2
    - always
    - 72
